version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6381:6381
            - 26381:26381
        volumes:
            - ./config/redis-slave.conf:/usr/local/etc/redis/redis.conf
            - ./config/sentinel.conf:/usr/local/etc/redis/sentinel.conf
        command: >
            sh -c "redis-server /usr/local/etc/redis/redis.conf &&
                   redis-server /usr/local/etc/redis/sentinel.conf --sentinel"
        network_mode: bridge
